version: '2.1'
services:
  nepal-it-pool:
    container_name: nepal-it-pool
    build: ./
    environment:
      - VIRTUAL_HOST=itpool.pv
      - APP_ENV=dev
      - ELASTIC_HOST_URL=http://elasticsearch:9200
      - GIN_MODE=release
    volumes:
      - ./app:/go/src/github.com/user/sites/app
    ports:
      - "5000:8080"
    depends_on:
       elasticsearch :
          condition: service_healthy
    links:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.4.2'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 2s
      timeout: 30s
      retries: 50
