name: Build and Push
on:
  push:
    branches:
      - master
jobs:
  build_publish_gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Authenticate with google cloud

        uses: actions/gcloud/auth@master
        env:
          GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Push to Goolge Cloud Registry
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud auth configure-docker && docker build -t nepal-it-pool . &&  docker tag  nepal-it-pool:latest gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/nepal-it-pool && docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/nepal-it-pool:latest"

      - name: Deploy to cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/nepal-it-pool --platform managed  --region us-central1 --project=${{ secrets.GCLOUD_PROJECT_ID }}"
